/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFrameHome.java
 *
 * Created on Oct 30, 2013, 10:26:38 PM
 */
package instance;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedInputStream;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.border.EmptyBorder;
import instance.*;
/**
 *
 * @author user
 */
@SuppressWarnings({ "unused", "serial" })
public class JFrameHome extends javax.swing.JFrame {

	
    private static class jframeTitle {

        public jframeTitle() {
        	
        }
    }

    
    
    /** Creates new form JFrameHome */
    public JFrameHome() {
    	
    	JPanel contentPane = new JPanel() {  
    		                public void paintComponent(Graphics g) {  
    		                     Image img = Toolkit.getDefaultToolkit().getImage(  
                                    JFrameHome.class.getResource("BG.jpg"));  
    		                      g.drawImage(img, 0, 0, this.getWidth(), this.getHeight(), this);  
    		                }  
    		        };  
    		          contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));  
    		           contentPane.setLayout(new BorderLayout(0, 0));  
    		           setContentPane(contentPane);  
    		           
    		           setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
    	
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jButtonList = new javax.swing.JButton();
        jButtonCreate = new javax.swing.JButton();
        jButtonTerminate = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuView = new javax.swing.JMenu();
        jMenuItemList = new javax.swing.JMenuItem();
        jMenuItemCreate = new javax.swing.JMenuItem();
        jMenuItemTerminate = new javax.swing.JMenuItem();

        setIconImage(Toolkit.getDefaultToolkit().getImage("Cloud.png"));
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ALL OPERATIONS");
        setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        setBackground(Color.lightGray);
        
       
        

        jButtonList.setBackground(new java.awt.Color(0, 153, 153));
        jButtonList.setForeground(new java.awt.Color(255, 255, 255));
        jButtonList.setText("LIST ALL INSTANCES");
        jButtonList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListActionPerformed(evt);
            }
        });

        jButtonCreate.setBackground(new java.awt.Color(0, 153, 153));
        jButtonCreate.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCreate.setText("CREATE A NEW INSTANCE");
        jButtonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateActionPerformed(evt);
            }
        });

        jButtonTerminate.setBackground(new java.awt.Color(0, 153, 153));
        jButtonTerminate.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTerminate.setText("TERMINATE A INSTANCE");
        jButtonTerminate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTerminateActionPerformed(evt);
            }
        });

        jMenuFile.setBackground(new java.awt.Color(255, 255, 255));
        jMenuFile.setText("FILE");
        jMenuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFileActionPerformed(evt);
            }
        });

        jMenuItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jMenuItemExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/instance/twitter-20x20.png"))); // NOI18N
        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemExit);

        jMenuBar1.add(jMenuFile);

        jMenuView.setBackground(new java.awt.Color(255, 255, 255));
        jMenuView.setText("VIEW");
        jMenuView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuViewActionPerformed(evt);
            }
        });

        jMenuItemList.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/instance/twitter-20x20.png"))); // NOI18N
        jMenuItemList.setText("LIST");
        jMenuItemList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListActionPerformed(evt);
            }
        });
        jMenuView.add(jMenuItemList);

        jMenuItemCreate.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/instance/twitter-20x20.png"))); // NOI18N
        jMenuItemCreate.setText("CREATE");
        jMenuItemCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCreateActionPerformed(evt);
            }
        });
        jMenuView.add(jMenuItemCreate);

        jMenuItemTerminate.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemTerminate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/instance/twitter-20x20.png"))); // NOI18N
        jMenuItemTerminate.setText("TERMINATE");
        jMenuItemTerminate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTerminateActionPerformed(evt);
            }
        });
        jMenuView.add(jMenuItemTerminate);

        jMenuBar1.add(jMenuView);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonTerminate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(jButtonCreate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(jButtonList, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                .addGap(224, 224, 224))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jButtonList)
                .addGap(40, 40, 40)
                .addComponent(jButtonCreate)
                .addGap(41, 41, 41)
                .addComponent(jButtonTerminate)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private static void jButtonListActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
         //new JFrameHome().setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       // JFrameList jFrameList = new JFrameList();
       //dispose();
        
    	
    	JFrameList.main(null);
    	
       
    	
    	
      
}                                        

	private void jButtonCreateActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        JFrameScale.main(null);
    }                                        

    private void jButtonTerminateActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        JFrameTerminate.main(null);
    }                                        

    private void jMenuFileActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
}                                      

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        System.exit(0);
        
    }                                          

    private void jMenuViewActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
}

    private void jMenuItemListActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        JFrameList.main(null);
    }

    private void jMenuItemCreateActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        JFrameScale.main(null);
    }

    private void jMenuItemTerminateActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        JFrameTerminate.main(null);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    	
    	 try { 
             UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel"); 
         } catch (Exception ex) { 
             ex.printStackTrace(); 
         }
         
    	//JFrameList frame =new JFrameList();
    	
    	
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            
            @Override
            public void run() {
                new JFrameHome().setVisible(true);
                
                                                          
            }
        });
    }
    // Variables declaration - do not modify
    private javax.swing.JButton jButtonCreate;
    private javax.swing.JButton jButtonList;
    private javax.swing.JButton jButtonTerminate;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItemCreate;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemList;
    private javax.swing.JMenuItem jMenuItemTerminate;
    private javax.swing.JMenu jMenuView;
    // End of variables declaration
}
