/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFrameList.java
 *
 * Created on Oct 31, 2013, 1:27:26 AM
 */
package instance;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.FlowLayout;
import java.awt.Frame;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.MenuBar;
import java.awt.Toolkit;
import java.awt.Window;
import java.awt.event.ActionEvent;

import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JRootPane;
import javax.swing.UIManager;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author user
 */
@SuppressWarnings({ "serial", "unused" })
public class JFrameList extends javax.swing.JFrame {

    /** Creates new form JFrameList */
    public JFrameList() {
    	
    	JPanel contentPane = new JPanel() {  
            public void paintComponent(Graphics g) {  
                 Image img = Toolkit.getDefaultToolkit().getImage(  
                    JFrameHome.class.getResource("BG.jpg"));  
                  g.drawImage(img, 0, 0, this.getWidth(), this.getHeight(), this);  
            }  
    };  
      contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));  
       contentPane.setLayout(new BorderLayout(0, 0));  
       setContentPane(contentPane);  
       
       setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
    	
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     * @param  
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void abc(String[] id)
    {
    
		
    	try { 
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel"); 
        } catch (Exception ex) { 
            ex.printStackTrace(); 
        }
    	
    	
    	
    	 jMenuBar1 = new javax.swing.JMenuBar();
         jMenuFile = new javax.swing.JMenu();
         jMenuItemExit = new javax.swing.JMenuItem();
         jMenuView = new javax.swing.JMenu();
         jMenuItemList = new javax.swing.JMenuItem();
         jMenuItemCreate = new javax.swing.JMenuItem();
         jMenuItemTerminate = new javax.swing.JMenuItem();

         JFrame frame = new JFrame("LIST OF ALL RUNNING INSTANCES");
         frame.setIconImage(Toolkit.getDefaultToolkit().getImage("Cloud.png"));
         frame.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
         
         frame.setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        

         jButtonGetIDOfInstances.setBackground(new java.awt.Color(0, 153, 153));
         jButtonGetIDOfInstances.setForeground(new java.awt.Color(255, 255, 255));
         jButtonGetIDOfInstances.setText("GET ID OF ALL INSTANCES");
         jButtonGetIDOfInstances.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 jButtonGetIDOfInstancesActionPerformed(evt);
             }
         });

         listOfInstances.setBackground(new java.awt.Color(0, 153, 153));
         listOfInstances.setForeground(new java.awt.Color(255, 255, 255));
         listOfInstances.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 jButtonGetIDOfInstancesActionPerformed(evt);
             }
         });

         jMenuFile.setBackground(new java.awt.Color(255, 255, 255));
         jMenuFile.setText("FILE");
         jMenuFile.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 jMenuFileActionPerformed(evt);
             }
         });

         jMenuItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
         jMenuItemExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/instance/twitter-20x20.png"))); // NOI18N
         jMenuItemExit.setText("Exit");
         jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 jMenuItemExitActionPerformed(evt);
             }
         });
         jMenuFile.add(jMenuItemExit);

         jMenuBar1.add(jMenuFile);

         jMenuView.setBackground(new java.awt.Color(255, 255, 255));
         jMenuView.setText("VIEW");
         jMenuView.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 jMenuViewActionPerformed(evt);
             }
         });

         jMenuItemList.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
         jMenuItemList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/instance/twitter-20x20.png"))); // NOI18N
         jMenuItemList.setText("LIST");
         jMenuItemList.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 jMenuItemListActionPerformed(evt);
             }
         });
         jMenuView.add(jMenuItemList);

         jMenuItemCreate.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
         jMenuItemCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/instance/twitter-20x20.png"))); // NOI18N
         jMenuItemCreate.setText("CREATE");
         jMenuItemCreate.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 jMenuItemCreateActionPerformed(evt);
             }
         });
         jMenuView.add(jMenuItemCreate);

         jMenuItemTerminate.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
         jMenuItemTerminate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/instance/twitter-20x20.png"))); // NOI18N
         jMenuItemTerminate.setText("TERMINATE");
         jMenuItemTerminate.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 jMenuItemTerminateActionPerformed(evt);
             }
         });
         jMenuView.add(jMenuItemTerminate);

         jMenuBar1.add(jMenuView);
         
         jMenuBar1.setMaximumSize(getMaximumSize());
         jMenuBar1.setMaximumSize(getMaximumSize());
         

         setJMenuBar(jMenuBar1);
         
        // UIManager.put("MenuItem.background", Color.CYAN);
         
         
         frame.add(jMenuBar1);

       
        

         pack();
    	
    	
    	JButton jButtonList=new JButton();
		 jButtonList.setBackground(new java.awt.Color(0, 153, 153));
	        jButtonList.setForeground(new java.awt.Color(255, 255, 255));
	        jButtonList.setText("LIST OF ALL INSTANCES");
	        jButtonList.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	               
	            }
	        });
    	
    	
    	
	        
        
        
    	@SuppressWarnings({ "rawtypes", "unchecked" })
		JList list = new JList(id);
        
    	
    	JPanel panel = new JPanel() {  
            public void paintComponent(Graphics g) {  
                 Image img = Toolkit.getDefaultToolkit().getImage(  
                    JFrameHome.class.getResource("BG.jpg"));  
                  g.drawImage(img, 0, 0, this.getWidth(), this.getHeight(), this);  
            }  
    };  
    panel.setSize(getPreferredSize());
     panel.setBorder(new EmptyBorder(50, 50, 50, 500));  
     // panel.setBorder(new EmptyBorder(100, 100, 100, 1000));  
     // panel.setLayout(new BoxLayout(panel, HEIGHT));
      panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
       setContentPane(panel);  
       list.setAlignmentX(Component.CENTER_ALIGNMENT);
       jButtonList.setAlignmentX(Component.CENTER_ALIGNMENT);
       list.getScrollableTracksViewportHeight();
       list.getScrollableTracksViewportWidth();
       list.setFixedCellWidth(630);
    	
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       	panel.add(list);
       	panel.add(jButtonList);
       
       	frame.add(panel);
//       	frame.setSize(700, 500);
       	frame.setSize(1400, 1000);
		frame.setVisible(true);
		
		
        //frame.setLayout(getLayout());
		
    }
    
    private void initComponents() {

        jButtonGetIDOfInstances = new javax.swing.JButton();
        listOfInstances = new java.awt.List();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuView = new javax.swing.JMenu();
        jMenuItemList = new javax.swing.JMenuItem();
        jMenuItemCreate = new javax.swing.JMenuItem();
        jMenuItemTerminate = new javax.swing.JMenuItem();

        setIconImage(Toolkit.getDefaultToolkit().getImage("Cloud.png"));
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LIST OF ALL RUNNING INSTANCES");
        
        
        
       

        jButtonGetIDOfInstances.setBackground(new java.awt.Color(0, 153, 153));
        jButtonGetIDOfInstances.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGetIDOfInstances.setText("GET ID OF ALL INSTANCES");
        jButtonGetIDOfInstances.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGetIDOfInstancesActionPerformed(evt);
            }
        });

        listOfInstances.setBackground(new java.awt.Color(0, 153, 153));
        listOfInstances.setForeground(new java.awt.Color(255, 255, 255));
        listOfInstances.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGetIDOfInstancesActionPerformed(evt);
            }
        });

        jMenuFile.setBackground(new java.awt.Color(255, 255, 255));
        jMenuFile.setText("FILE");
        jMenuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFileActionPerformed(evt);
            }
        });

        jMenuItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jMenuItemExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/instance/twitter-20x20.png"))); // NOI18N
        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemExit);

        jMenuBar1.add(jMenuFile);

        jMenuView.setBackground(new java.awt.Color(255, 255, 255));
        jMenuView.setText("VIEW");
        jMenuView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuViewActionPerformed(evt);
            }
        });

        jMenuItemList.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/instance/twitter-20x20.png"))); // NOI18N
        jMenuItemList.setText("LIST");
        jMenuItemList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListActionPerformed(evt);
            }
        });
        jMenuView.add(jMenuItemList);

        jMenuItemCreate.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/instance/twitter-20x20.png"))); // NOI18N
        jMenuItemCreate.setText("CREATE");
        jMenuItemCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCreateActionPerformed(evt);
            }
        });
        jMenuView.add(jMenuItemCreate);

        jMenuItemTerminate.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemTerminate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/instance/twitter-20x20.png"))); // NOI18N
        jMenuItemTerminate.setText("TERMINATE");
        jMenuItemTerminate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTerminateActionPerformed(evt);
            }
        });
        jMenuView.add(jMenuItemTerminate);

        jMenuBar1.add(jMenuView);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(117, 117, 117)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(jButtonGetIDOfInstances, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                    .addGap(117, 117, 117)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(76, 76, 76)
                    .addComponent(jButtonGetIDOfInstances)
                    .addGap(45, 45, 45)
                    .addContainerGap(55, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>

                                       

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        System.exit(0);
    }

    private void jMenuFileActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
}

    private void jMenuItemListActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        JFrameList.main(null);
}

    private void jMenuItemCreateActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        JFrameScale.main(null);
}

    private void jMenuItemTerminateActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        JFrameTerminate.main(null);
}

    private void jMenuViewActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
}

    private void jButtonGetIDOfInstancesActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    	
    	try {
			LCTMain.init();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    	
       	abc(LCTMain.list());
        
    	
    
        
        	
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    	
    	
    	 try { 
             UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel"); 
         } catch (Exception ex) { 
             ex.printStackTrace(); 
         }
         
    	
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new JFrameList().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify
    private javax.swing.JButton jButtonGetIDOfInstances;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItemCreate;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemList;
    private javax.swing.JMenuItem jMenuItemTerminate;
    private javax.swing.JMenu jMenuView;
    private java.awt.List listOfInstances;
    // End of variables declaration
}
