/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFrameTerminate.java
 *
 * Created on Oct 31, 2013, 2:06:49 AM
 */
package instance;

import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author user
 */
@SuppressWarnings("serial")
public class JFrameTerminate extends javax.swing.JFrame {

    /** Creates new form JFrameTerminate */
    public JFrameTerminate() {
    	
    	JPanel contentPane = new JPanel() {  
            public void paintComponent(Graphics g) {  
                 Image img = Toolkit.getDefaultToolkit().getImage(  
                    JFrameHome.class.getResource("BG.jpg"));  
                  g.drawImage(img, 0, 0, this.getWidth(), this.getHeight(), this);  
            }  
    };  
      contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));  
       contentPane.setLayout(new BorderLayout(0, 0));  
       setContentPane(contentPane);  
    	
       setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
       
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jButtonTerminateSelectedInstance = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        listOfInstances = new java.awt.List();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuView = new javax.swing.JMenu();
        jMenuItemList = new javax.swing.JMenuItem();
        jMenuItemCreate = new javax.swing.JMenuItem();
        jMenuItemTerminate = new javax.swing.JMenuItem();

        setIconImage(Toolkit.getDefaultToolkit().getImage("Cloud.png"));
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TERMINATE INSTANCES");
        

        jButtonTerminateSelectedInstance.setBackground(new java.awt.Color(0, 153, 153));
        jButtonTerminateSelectedInstance.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTerminateSelectedInstance.setText("TERMINATE");
        jButtonTerminateSelectedInstance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTerminateSelectedInstanceActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("INSTANCE ID");

        listOfInstances.setBackground(new java.awt.Color(0, 153, 153));
        listOfInstances.setForeground(new java.awt.Color(255, 255, 255));
        listOfInstances.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listOfInstancesActionPerformed(evt);
            }
        });

        jMenuFile.setBackground(new java.awt.Color(255, 255, 255));
        jMenuFile.setText("FILE");
        jMenuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFileActionPerformed(evt);
            }
        });

        jMenuItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jMenuItemExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/instance/twitter-20x20.png"))); // NOI18N
        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemExit);

        jMenuBar1.add(jMenuFile);

        jMenuView.setBackground(new java.awt.Color(255, 255, 255));
        jMenuView.setText("VIEW");
        jMenuView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuViewActionPerformed(evt);
            }
        });

        jMenuItemList.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/instance/twitter-20x20.png"))); // NOI18N
        jMenuItemList.setText("LIST");
        jMenuItemList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListActionPerformed(evt);
            }
        });
        jMenuView.add(jMenuItemList);

        jMenuItemCreate.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/instance/twitter-20x20.png"))); // NOI18N
        jMenuItemCreate.setText("CREATE");
        jMenuItemCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCreateActionPerformed(evt);
            }
        });
        jMenuView.add(jMenuItemCreate);

        jMenuItemTerminate.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemTerminate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/instance/twitter-20x20.png"))); // NOI18N
        jMenuItemTerminate.setText("TERMINATE");
        jMenuItemTerminate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTerminateActionPerformed(evt);
            }
        });
        jMenuView.add(jMenuItemTerminate);

        jMenuBar1.add(jMenuView);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonTerminateSelectedInstance, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                .addGap(127, 127, 127))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                
                .addGap(47, 47, 47)
                .addComponent(jButtonTerminateSelectedInstance)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void jButtonTerminateSelectedInstanceActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    	try {
			LCTMain.init();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    	LCTMain.terminateLast();
    	
        JOptionPane.showMessageDialog(this, "ONE RUNNING INSTANCE IS TERMINATED");
    	
}                                        

    private void listOfInstancesActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        System.exit(0);
    }

    private void jMenuFileActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
}

    private void jMenuItemListActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        JFrameList.main(null);
}

    private void jMenuItemCreateActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        JFrameScale.main(null);
}

    private void jMenuItemTerminateActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        JFrameTerminate.main(null);
}

    private void jMenuViewActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    	
    	
    	 try { 
             UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel"); 
         } catch (Exception ex) { 
             ex.printStackTrace(); 
         }
         
    	
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JFrameTerminate().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonTerminateSelectedInstance;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItemCreate;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemList;
    private javax.swing.JMenuItem jMenuItemTerminate;
    private javax.swing.JMenu jMenuView;
    private java.awt.List listOfInstances;
    // End of variables declaration
}
